name: IITM Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 22f3002344@ds.study.iitm.ac.in
        run: echo "Hello World"

      - name: Finish
        run: echo "Done"
